language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19


before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-26"

script:
    - ./gradlew assembleDebug
